global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sentinelclear-api"
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - "tasks.api-gateway"
        type: "A"
        port: 8000
