"""Add transaction_pin_hash and missing fields

Revision ID: e34a218d71d2
Revises: 011
Create Date: 2026-04-17 17:09:23.244457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34a218d71d2'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_snapshots_account_id_key', 'balance_snapshots', type_='unique')
    op.drop_index('ix_balance_snapshots_account_id', table_name='balance_snapshots')
    op.create_index(op.f('ix_balance_snapshots_account_id'), 'balance_snapshots', ['account_id'], unique=True)
    op.drop_index('ix_beneficiaries_recipient', table_name='beneficiaries')
    op.create_index(op.f('ix_beneficiaries_recipient_account_id'), 'beneficiaries', ['recipient_account_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('transfers', sa.Column('source_ip', sa.String(length=45), nullable=True))
    op.add_column('transfers', sa.Column('source_city', sa.String(length=100), nullable=True))
    op.add_column('transfers', sa.Column('auth_challenge_id', sa.String(length=36), nullable=True))
    op.add_column('transfers', sa.Column('checker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfers', 'users', ['checker_id'], ['id'])
    op.add_column('users', sa.Column('transaction_pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_index('ix_whitelist_contact_id', table_name='whitelisted_contacts')
    op.drop_index('ix_whitelist_user_id', table_name='whitelisted_contacts')
    op.create_index(op.f('ix_whitelisted_contacts_contact_account_id'), 'whitelisted_contacts', ['contact_account_id'], unique=False)
    op.create_index(op.f('ix_whitelisted_contacts_user_id'), 'whitelisted_contacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelisted_contacts_user_id'), table_name='whitelisted_contacts')
    op.drop_index(op.f('ix_whitelisted_contacts_contact_account_id'), table_name='whitelisted_contacts')
    op.create_index('ix_whitelist_user_id', 'whitelisted_contacts', ['user_id'], unique=False)
    op.create_index('ix_whitelist_contact_id', 'whitelisted_contacts', ['contact_account_id'], unique=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'transaction_pin_hash')
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'checker_id')
    op.drop_column('transfers', 'auth_challenge_id')
    op.drop_column('transfers', 'source_city')
    op.drop_column('transfers', 'source_ip')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_beneficiaries_recipient_account_id'), table_name='beneficiaries')
    op.create_index('ix_beneficiaries_recipient', 'beneficiaries', ['recipient_account_id'], unique=False)
    op.drop_index(op.f('ix_balance_snapshots_account_id'), table_name='balance_snapshots')
    op.create_index('ix_balance_snapshots_account_id', 'balance_snapshots', ['account_id'], unique=False)
    op.create_unique_constraint('balance_snapshots_account_id_key', 'balance_snapshots', ['account_id'])
    # ### end Alembic commands ###
